In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_parquet('/opt/data/california-worldcover-chips-osm-multilabels.parquet')
df.shape

(83609, 8)

In [3]:
df.head()

onehot_count  \
chip_id                                                            
193c3415fc237  [24, 24, 1344, 388, 472, 21, 453, 2, 8, 0, 0, ...   
1639b12583426  [148, 148, 4171, 1245, 1891, 52, 938, 13, 32, ...   
253904d963d6a  [65, 65, 200, 104, 76, 0, 18, 2, 0, 0, 0, 0, 0...   
00530dca88d4a  [9, 9, 4897, 688, 4026, 0, 172, 10, 1, 0, 0, 0...   
0e554bbdbe661  [80, 80, 4358, 1262, 2386, 59, 597, 27, 27, 0,...   

                                                     onehot_area  \
chip_id                                                            
193c3415fc237  [58033.967200952815, 58033.967200952815, 23937...   
1639b12583426  [160073.78667008967, 160073.78667008967, 80191...   
253904d963d6a  [101980.95118259436, 101980.95118259436, 71246...   
00530dca88d4a  [17637.908172952746, 17637.908172952746, 10930...   
0e554bbdbe661  [131950.60085068244, 131950.60085068244, 98472...   

                                                   onehot_length  \
chip_id                                                            
193c3415fc237  [4913.205774298301, 4913.205774298301, 74943.4...   
1639b12583426  [20966.344659970102, 20966.344659970102, 24881...   
253904d963d6a  [10597.989172272657, 10597.989172272657, 16664...   
00530dca88d4a  [1925.4953839123748, 1925.4953839123748, 32065...   
0e554bbdbe661  [13536.03447682216, 13536.03447682216, 283601....   

                                                   string_labels    col  \
chip_id                                                                   
193c3415fc237  [amenity=*, amenity=parking, building=*, build...  78080   
1639b12583426  [amenity=*, amenity=parking, building=*, build...  78080   
253904d963d6a  [amenity=*, amenity=parking, building=*, build...  77824   
00530dca88d4a  [amenity=*, amenity=parking, building=*, build...  77824   
0e554bbdbe661  [amenity=*, amenity=parking, building=*, build...  78080   

                 row                                           geometry  split  
chip_id                                                                         
193c3415fc237  96000  b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x05\x00...  train  
1639b12583426  95744  b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x05\x00...  train  
253904d963d6a  95744  b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x05\x00...  train  
00530dca88d4a  95488  b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x05\x00...  train  
0e554bbdbe661  95488  b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x05\x00...  train

In [4]:
OSM_counts = np.stack(df.onehot_count)
print(OSM_counts.shape)
print(OSM_counts)

(83609, 99)
[[  24   24 1344 ...   53    0    0]
 [ 148  148 4171 ...  166    0    1]
 [  65   65  200 ...   29    0    1]
 ...
 [   4    4    1 ...   77    0   40]
 [   0    0    0 ...    4    0   12]
 [   0    0    0 ...    0    0    7]]


In [5]:
def autocomplete_query(
    constraints: tuple[int],  # user contraints, ex: (0,0,...,1,-1)
    df: pd.DataFrame,
    n_samples: int = 1,
):
    df = df.query("split == 'train'")
    counts = np.stack(df.onehot_count)
    kept_rows_mask = np.array((True,) * df.shape[0])  # mask of kept rows
    constrained_cols_ix = np.nonzero(constraints)[0]  # indices of constrained columns
    
    for col_ix in constrained_cols_ix:
        constraint = constraints[col_ix]
        if constraint == 1:
            kept_rows_mask *= (counts[:, col_ix] > 0)
        elif constraint == -1:
            kept_rows_mask *= (counts[:, col_ix] == 0)

    print(kept_rows_mask.sum())
    if kept_rows_mask.sum() > 0:
        df = df.iloc[kept_rows_mask]  # keep rows that satisfy the constraints
        return df.sample(n=n_samples, replace=True, axis=0, random_state=42)  # sample w replacement
    else:
        return df[0:0]  # return 0 rows

In [6]:
example_constraints = np.array((0,) * 99)
example_constraints[0] = 1
example_constraints[1] = 1
example_constraints[2] = -1
example_constraints[3] = -1
example_constraints[10] = 1
example_constraints

array([ 1,  1, -1, -1,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [7]:
# %%debug
autocomplete_query(constraints=example_constraints, df=df, n_samples=20)

12


onehot_count  \
chip_id                                                            
29a5d117b899a  [1, 1, 0, 0, 0, 0, 0, 0, 0, 31, 2, 29, 0, 49, ...   
055c53964deb1  [5, 5, 0, 0, 0, 0, 0, 0, 0, 9, 9, 0, 0, 12, 0,...   
10c312357b680  [1, 1, 0, 0, 0, 0, 0, 0, 0, 12, 3, 9, 0, 11, 5...   
1e164cc44d2c8  [1, 1, 0, 0, 0, 0, 0, 0, 0, 6, 2, 3, 1, 102, 0...   
35bfad9302303  [1, 1, 0, 0, 0, 0, 0, 0, 0, 9, 9, 0, 0, 27, 4,...   
29a5d117b899a  [1, 1, 0, 0, 0, 0, 0, 0, 0, 31, 2, 29, 0, 49, ...   
065dc6317a55e  [1, 1, 0, 0, 0, 0, 0, 0, 0, 7, 5, 2, 0, 51, 3,...   
1c9b769f462fe  [2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 4, 2, ...   
29a5d117b899a  [1, 1, 0, 0, 0, 0, 0, 0, 0, 31, 2, 29, 0, 49, ...   
10c312357b680  [1, 1, 0, 0, 0, 0, 0, 0, 0, 12, 3, 9, 0, 11, 5...   
10c312357b680  [1, 1, 0, 0, 0, 0, 0, 0, 0, 12, 3, 9, 0, 11, 5...   
1e164cc44d2c8  [1, 1, 0, 0, 0, 0, 0, 0, 0, 6, 2, 3, 1, 102, 0...   
35bfad9302303  [1, 1, 0, 0, 0, 0, 0, 0, 0, 9, 9, 0, 0, 27, 4,...   
055c53964deb1  [5, 5, 0, 0, 0, 0, 0, 0, 0, 9, 9, 0, 0, 12, 0,...   
1e164cc44d2c8  [1, 1, 0, 0, 0, 0, 0, 0, 0, 6, 2, 3, 1, 102, 0...   
1e164cc44d2c8  [1, 1, 0, 0, 0, 0, 0, 0, 0, 6, 2, 3, 1, 102, 0...   
1c9b769f462fe  [2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 4, 2, ...   
12ec017464c44  [1, 1, 0, 0, 0, 0, 0, 0, 0, 6, 6, 0, 0, 6, 3, ...   
35bfad9302303  [1, 1, 0, 0, 0, 0, 0, 0, 0, 9, 9, 0, 0, 27, 4,...   
0f5d004262edb  [8, 8, 0, 0, 0, 0, 0, 0, 0, 6, 3, 3, 0, 21, 19...   

                                                     onehot_area  \
chip_id                                                            
29a5d117b899a  [1387.1771053231764, 1387.1771053231764, 0.0, ...   
055c53964deb1  [1588.7106419486881, 1588.7106419486881, 0.0, ...   
10c312357b680  [1936.0009179324309, 1936.0009179324309, 0.0, ...   
1e164cc44d2c8  [1480.8195388180136, 1480.8195388180136, 0.0, ...   
35bfad9302303  [5441.174967043069, 5441.174967043069, 0.0, 0....   
29a5d117b899a  [1387.1771053231764, 1387.1771053231764, 0.0, ...   
065dc6317a55e  [705.921544141705, 705.921544141705, 0.0, 0.0,...   
1c9b769f462fe  [2136.42317929564, 2136.42317929564, 0.0, 0.0,...   
29a5d117b899a  [1387.1771053231764, 1387.1771053231764, 0.0, ...   
10c312357b680  [1936.0009179324309, 1936.0009179324309, 0.0, ...   
10c312357b680  [1936.0009179324309, 1936.0009179324309, 0.0, ...   
1e164cc44d2c8  [1480.8195388180136, 1480.8195388180136, 0.0, ...   
35bfad9302303  [5441.174967043069, 5441.174967043069, 0.0, 0....   
055c53964deb1  [1588.7106419486881, 1588.7106419486881, 0.0, ...   
1e164cc44d2c8  [1480.8195388180136, 1480.8195388180136, 0.0, ...   
1e164cc44d2c8  [1480.8195388180136, 1480.8195388180136, 0.0, ...   
1c9b769f462fe  [2136.42317929564, 2136.42317929564, 0.0, 0.0,...   
12ec017464c44  [9741.08868745153, 9741.08868745153, 0.0, 0.0,...   
35bfad9302303  [5441.174967043069, 5441.174967043069, 0.0, 0....   
0f5d004262edb  [2189.6279515159704, 2189.6279515159704, 0.0, ...   

                                                   onehot_length  \
chip_id                                                            
29a5d117b899a  [175.3093662846612, 175.3093662846612, 0.0, 0....   
055c53964deb1  [372.32445834181027, 372.32445834181027, 0.0, ...   
10c312357b680  [189.24664394866443, 189.24664394866443, 0.0, ...   
1e164cc44d2c8  [186.3072349785997, 186.3072349785997, 0.0, 0....   
35bfad9302303  [295.1525894512135, 295.1525894512135, 0.0, 0....   
29a5d117b899a  [175.3093662846612, 175.3093662846612, 0.0, 0....   
065dc6317a55e  [111.81848307312679, 111.81848307312679, 0.0, ...   
1c9b769f462fe  [318.6417921581011, 318.6417921581011, 0.0, 0....   
29a5d117b899a  [175.3093662846612, 175.3093662846612, 0.0, 0....   
10c312357b680  [189.24664394866443, 189.24664394866443, 0.0, ...   
10c312357b680  [189.24664394866443, 189.24664394866443, 0.0, ...   
1e164cc44d2c8  [186.3072349785997, 186.3072349785997, 0.0, 0....   
35bfad9302303  [295.1525894512135, 295.1525894512135, 0.0, 0....   
055c53964deb1  [372.32445834181027, 37